apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: acrthawatcdazusw3sbx001.azurecr.io/myweb:0.0.1-SNAPSHOT
        ports:
        - containerPort: 80